-- Test: Verify Dynamic Tables are refreshing (have recent data)
-- AGG_FRANCHISE_PERFORMANCE should have data
SELECT 'AGG_FRANCHISE_PERFORMANCE empty' AS error
WHERE NOT EXISTS (
    SELECT 1 FROM SONY_DE.STUDIO_OPS.AGG_FRANCHISE_PERFORMANCE
)

UNION ALL

SELECT 'AGG_FAN_LIFETIME_VALUE empty' AS error
WHERE NOT EXISTS (
    SELECT 1 FROM SONY_DE.MARKETING.AGG_FAN_LIFETIME_VALUE
)
