-- =============================================================================
-- STEP 2: RBAC (Role-Based Access Control) SETUP
-- Sony Pictures Entertainment Data Engineering Demo
-- =============================================================================
-- Run as: SECURITYADMIN or ACCOUNTADMIN
-- Time: ~2 minutes
-- =============================================================================

USE ROLE SECURITYADMIN;

-- =============================================================================
-- 2.1 ACCESS ROLES (Schema-level privileges)
-- =============================================================================

-- Read-only access roles
CREATE ROLE IF NOT EXISTS SONY_DE_BRONZE_R COMMENT = 'Read access to SONY_DE.BRONZE (Raw)';
CREATE ROLE IF NOT EXISTS SONY_DE_SILVER_R COMMENT = 'Read access to SONY_DE.SILVER (Staging)';
CREATE ROLE IF NOT EXISTS SONY_DE_SECURE_R COMMENT = 'Read access to SONY_DE.SECURE (PII vault)';
CREATE ROLE IF NOT EXISTS SONY_DE_GOLD_R COMMENT = 'Read access to SONY_DE.GOLD (Dims/Facts)';
CREATE ROLE IF NOT EXISTS SONY_DE_PLATINUM_R COMMENT = 'Read access to SONY_DE.PLATINUM (Aggregates)';
CREATE ROLE IF NOT EXISTS SONY_DE_GOVERNANCE_R COMMENT = 'Read access to SONY_DE.GOVERNANCE (Data quality)';
CREATE ROLE IF NOT EXISTS SONY_DE_ANALYTICS_R COMMENT = 'Read access to SONY_DE.ANALYTICS (Semantic views)';

-- Read/Write access roles (for ETL)
CREATE ROLE IF NOT EXISTS SONY_DE_BRONZE_RW COMMENT = 'Read/Write access to SONY_DE.BRONZE';
CREATE ROLE IF NOT EXISTS SONY_DE_SILVER_RW COMMENT = 'Read/Write access to SONY_DE.SILVER';
CREATE ROLE IF NOT EXISTS SONY_DE_GOLD_RW COMMENT = 'Read/Write access to SONY_DE.GOLD';
CREATE ROLE IF NOT EXISTS SONY_DE_PLATINUM_RW COMMENT = 'Read/Write access to SONY_DE.PLATINUM';

-- =============================================================================
-- 2.2 FUNCTIONAL ROLES (Persona-based)
-- =============================================================================

CREATE ROLE IF NOT EXISTS SONY_DE_DATA_ENGINEER COMMENT = 'Data Engineer - Full pipeline access';
CREATE ROLE IF NOT EXISTS SONY_DE_ANALYST COMMENT = 'Analyst - Read access to Gold/Platinum layers';
CREATE ROLE IF NOT EXISTS SONY_DE_DATA_STEWARD COMMENT = 'Data Steward - Governance and quality access';
CREATE ROLE IF NOT EXISTS SONY_DE_PII_ADMIN COMMENT = 'PII Admin - Access to secure/PII data';

-- =============================================================================
-- 2.3 GRANT DATABASE USAGE TO ACCESS ROLES
-- =============================================================================

-- All roles need database usage
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_BRONZE_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_SILVER_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_SECURE_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_GOLD_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_PLATINUM_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_ANALYTICS_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_BRONZE_RW;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_SILVER_RW;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_GOLD_RW;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_PLATINUM_RW;

-- =============================================================================
-- 2.4 GRANT SCHEMA PRIVILEGES TO ACCESS ROLES
-- =============================================================================

-- BRONZE schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_R;

-- BRONZE schema (Read/Write)
GRANT USAGE ON SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_RW;
GRANT CREATE TABLE, CREATE STREAM, CREATE TASK ON SCHEMA SONY_DE.BRONZE TO ROLE SONY_DE_BRONZE_RW;

-- SILVER schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_R;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_R;

-- SILVER schema (Read/Write)
GRANT USAGE ON SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_RW;
GRANT CREATE TABLE, CREATE DYNAMIC TABLE ON SCHEMA SONY_DE.SILVER TO ROLE SONY_DE_SILVER_RW;

-- SECURE schema (Read - PII)
GRANT USAGE ON SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;

-- GOLD schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_R;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_R;

-- GOLD schema (Read/Write)
GRANT USAGE ON SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_RW;
GRANT CREATE TABLE, CREATE DYNAMIC TABLE ON SCHEMA SONY_DE.GOLD TO ROLE SONY_DE_GOLD_RW;

-- PLATINUM schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_R;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_R;

-- PLATINUM schema (Read/Write)
GRANT USAGE ON SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_RW;
GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_RW;
GRANT CREATE DYNAMIC TABLE ON SCHEMA SONY_DE.PLATINUM TO ROLE SONY_DE_PLATINUM_RW;

-- GOVERNANCE schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT SELECT ON ALL VIEWS IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;

-- ANALYTICS schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.ANALYTICS TO ROLE SONY_DE_ANALYTICS_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.ANALYTICS TO ROLE SONY_DE_ANALYTICS_R;
GRANT SELECT ON ALL VIEWS IN SCHEMA SONY_DE.ANALYTICS TO ROLE SONY_DE_ANALYTICS_R;
GRANT READ ON ALL STAGES IN SCHEMA SONY_DE.ANALYTICS TO ROLE SONY_DE_ANALYTICS_R;

-- =============================================================================
-- 2.5 GRANT ACCESS ROLES TO FUNCTIONAL ROLES
-- =============================================================================

-- Data Engineer: Full pipeline access
GRANT ROLE SONY_DE_BRONZE_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_SILVER_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_GOLD_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_PLATINUM_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_GOVERNANCE_R TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_ANALYTICS_R TO ROLE SONY_DE_DATA_ENGINEER;

-- Analyst: Read access to Gold/Platinum layers
GRANT ROLE SONY_DE_GOLD_R TO ROLE SONY_DE_ANALYST;
GRANT ROLE SONY_DE_PLATINUM_R TO ROLE SONY_DE_ANALYST;
GRANT ROLE SONY_DE_ANALYTICS_R TO ROLE SONY_DE_ANALYST;

-- Data Steward: Governance and quality access
GRANT ROLE SONY_DE_GOVERNANCE_R TO ROLE SONY_DE_DATA_STEWARD;
GRANT ROLE SONY_DE_GOLD_R TO ROLE SONY_DE_DATA_STEWARD;
GRANT ROLE SONY_DE_SILVER_R TO ROLE SONY_DE_DATA_STEWARD;

-- PII Admin: Secure data access
GRANT ROLE SONY_DE_SECURE_R TO ROLE SONY_DE_PII_ADMIN;
GRANT ROLE SONY_DE_GOLD_R TO ROLE SONY_DE_PII_ADMIN;

-- =============================================================================
-- 2.6 GRANT FUNCTIONAL ROLES TO SYSADMIN (role hierarchy)
-- =============================================================================

GRANT ROLE SONY_DE_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_DATA_STEWARD TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_PII_ADMIN TO ROLE SYSADMIN;

-- =============================================================================
-- 2.7 WAREHOUSE ACCESS
-- =============================================================================

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_DATA_STEWARD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_PII_ADMIN;

-- =============================================================================
-- 2.8 VERIFICATION
-- =============================================================================
SHOW ROLES LIKE 'SONY_DE%';

-- Expected: 15+ roles (access + functional roles)
-- Role hierarchy diagram:
--
--   SYSADMIN
--       │
--       ├── SONY_DE_DATA_ENGINEER
--       │       ├── SONY_DE_BRONZE_RW
--       │       ├── SONY_DE_SILVER_RW
--       │       ├── SONY_DE_GOLD_RW
--       │       ├── SONY_DE_PLATINUM_RW
--       │       ├── SONY_DE_GOVERNANCE_R
--       │       └── SONY_DE_ANALYTICS_R
--       │
--       ├── SONY_DE_ANALYST
--       │       ├── SONY_DE_GOLD_R
--       │       ├── SONY_DE_PLATINUM_R
--       │       └── SONY_DE_ANALYTICS_R
--       │
--       ├── SONY_DE_DATA_STEWARD
--       │       ├── SONY_DE_GOVERNANCE_R
--       │       ├── SONY_DE_GOLD_R
--       │       └── SONY_DE_SILVER_R
--       │
--       └── SONY_DE_PII_ADMIN
--               ├── SONY_DE_SECURE_R
--               └── SONY_DE_GOLD_R
