-- =============================================================================
-- SONY_DE RBAC Setup Script
-- Run this script with ACCOUNTADMIN or SECURITYADMIN role
-- =============================================================================

USE ROLE SECURITYADMIN;

-- =============================================================================
-- ACCESS ROLES (Schema-level privileges)
-- =============================================================================

-- Read-only access roles
CREATE ROLE IF NOT EXISTS SONY_DE_RAW_R COMMENT = 'Read access to SONY_DE.RAW (Bronze)';
CREATE ROLE IF NOT EXISTS SONY_DE_STG_R COMMENT = 'Read access to SONY_DE.STG (Silver staging)';
CREATE ROLE IF NOT EXISTS SONY_DE_SECURE_R COMMENT = 'Read access to SONY_DE.SECURE (PII vault)';
CREATE ROLE IF NOT EXISTS SONY_DE_DIMS_R COMMENT = 'Read access to SONY_DE.DIMS (Gold dimensions)';
CREATE ROLE IF NOT EXISTS SONY_DE_FACTS_R COMMENT = 'Read access to SONY_DE.FACTS (Gold facts)';
CREATE ROLE IF NOT EXISTS SONY_DE_STUDIO_OPS_R COMMENT = 'Read access to SONY_DE.STUDIO_OPS (Studio aggregates)';
CREATE ROLE IF NOT EXISTS SONY_DE_MARKETING_R COMMENT = 'Read access to SONY_DE.MARKETING (Marketing aggregates)';
CREATE ROLE IF NOT EXISTS SONY_DE_GOVERNANCE_R COMMENT = 'Read access to SONY_DE.GOVERNANCE (Data quality)';

-- Read/Write access roles (for ETL)
CREATE ROLE IF NOT EXISTS SONY_DE_RAW_RW COMMENT = 'Read/Write access to SONY_DE.RAW';
CREATE ROLE IF NOT EXISTS SONY_DE_STG_RW COMMENT = 'Read/Write access to SONY_DE.STG';
CREATE ROLE IF NOT EXISTS SONY_DE_DIMS_RW COMMENT = 'Read/Write access to SONY_DE.DIMS';
CREATE ROLE IF NOT EXISTS SONY_DE_FACTS_RW COMMENT = 'Read/Write access to SONY_DE.FACTS';
CREATE ROLE IF NOT EXISTS SONY_DE_GOLD_RW COMMENT = 'Read/Write access to all Gold schemas';

-- =============================================================================
-- FUNCTIONAL ROLES (Persona-based)
-- =============================================================================

CREATE ROLE IF NOT EXISTS SONY_DE_DATA_ENGINEER COMMENT = 'Data Engineer - Full pipeline access';
CREATE ROLE IF NOT EXISTS SONY_DE_ANALYST COMMENT = 'Analyst - Read access to Gold layer';
CREATE ROLE IF NOT EXISTS SONY_DE_MARKETING_ANALYST COMMENT = 'Marketing Analyst - Marketing schema access';
CREATE ROLE IF NOT EXISTS SONY_DE_STUDIO_ANALYST COMMENT = 'Studio Analyst - Studio ops schema access';
CREATE ROLE IF NOT EXISTS SONY_DE_DATA_STEWARD COMMENT = 'Data Steward - Governance and quality access';
CREATE ROLE IF NOT EXISTS SONY_DE_PII_ADMIN COMMENT = 'PII Admin - Access to secure/PII data';

-- =============================================================================
-- GRANT PRIVILEGES TO ACCESS ROLES
-- =============================================================================

-- Database usage for all
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_RAW_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_STG_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_SECURE_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_DIMS_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_FACTS_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_STUDIO_OPS_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_MARKETING_R;
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_GOVERNANCE_R;

-- RAW schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_R;

-- RAW schema (Read/Write)
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_RAW_RW;
GRANT USAGE ON SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_RW;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_RW;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA SONY_DE.RAW TO ROLE SONY_DE_RAW_RW;

-- STG schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_R;
GRANT SELECT ON ALL VIEWS IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_R;

-- STG schema (Read/Write)
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_STG_RW;
GRANT USAGE ON SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_RW;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA SONY_DE.STG TO ROLE SONY_DE_STG_RW;

-- SECURE schema (Read - PII)
GRANT USAGE ON SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.SECURE TO ROLE SONY_DE_SECURE_R;

-- DIMS schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_R;

-- DIMS schema (Read/Write)
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_DIMS_RW;
GRANT USAGE ON SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_DIMS_RW;

-- FACTS schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_R;

-- FACTS schema (Read/Write)
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_FACTS_RW;
GRANT USAGE ON SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_RW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_FACTS_RW;

-- STUDIO_OPS schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_STUDIO_OPS_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_STUDIO_OPS_R;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_STUDIO_OPS_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_STUDIO_OPS_R;

-- MARKETING schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_MARKETING_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_MARKETING_R;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_MARKETING_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_MARKETING_R;

-- GOVERNANCE schema (Read)
GRANT USAGE ON SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT SELECT ON ALL TABLES IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SONY_DE.GOVERNANCE TO ROLE SONY_DE_GOVERNANCE_R;

-- Gold RW (all gold schemas)
GRANT USAGE ON DATABASE SONY_DE TO ROLE SONY_DE_GOLD_RW;
GRANT USAGE ON SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_GOLD_RW;
GRANT USAGE ON SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_GOLD_RW;
GRANT USAGE ON SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_GOLD_RW;
GRANT USAGE ON SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_GOLD_RW;
GRANT ALL ON ALL TABLES IN SCHEMA SONY_DE.DIMS TO ROLE SONY_DE_GOLD_RW;
GRANT ALL ON ALL TABLES IN SCHEMA SONY_DE.FACTS TO ROLE SONY_DE_GOLD_RW;
GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.STUDIO_OPS TO ROLE SONY_DE_GOLD_RW;
GRANT ALL ON ALL DYNAMIC TABLES IN SCHEMA SONY_DE.MARKETING TO ROLE SONY_DE_GOLD_RW;

-- =============================================================================
-- GRANT ACCESS ROLES TO FUNCTIONAL ROLES
-- =============================================================================

-- Data Engineer: Full pipeline access
GRANT ROLE SONY_DE_RAW_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_STG_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_DIMS_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_FACTS_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_GOLD_RW TO ROLE SONY_DE_DATA_ENGINEER;
GRANT ROLE SONY_DE_GOVERNANCE_R TO ROLE SONY_DE_DATA_ENGINEER;

-- Analyst: Read access to Gold layer
GRANT ROLE SONY_DE_DIMS_R TO ROLE SONY_DE_ANALYST;
GRANT ROLE SONY_DE_FACTS_R TO ROLE SONY_DE_ANALYST;
GRANT ROLE SONY_DE_STUDIO_OPS_R TO ROLE SONY_DE_ANALYST;
GRANT ROLE SONY_DE_MARKETING_R TO ROLE SONY_DE_ANALYST;

-- Marketing Analyst: Marketing-focused access
GRANT ROLE SONY_DE_DIMS_R TO ROLE SONY_DE_MARKETING_ANALYST;
GRANT ROLE SONY_DE_FACTS_R TO ROLE SONY_DE_MARKETING_ANALYST;
GRANT ROLE SONY_DE_MARKETING_R TO ROLE SONY_DE_MARKETING_ANALYST;

-- Studio Analyst: Studio ops-focused access
GRANT ROLE SONY_DE_DIMS_R TO ROLE SONY_DE_STUDIO_ANALYST;
GRANT ROLE SONY_DE_FACTS_R TO ROLE SONY_DE_STUDIO_ANALYST;
GRANT ROLE SONY_DE_STUDIO_OPS_R TO ROLE SONY_DE_STUDIO_ANALYST;

-- Data Steward: Governance and quality
GRANT ROLE SONY_DE_GOVERNANCE_R TO ROLE SONY_DE_DATA_STEWARD;
GRANT ROLE SONY_DE_DIMS_R TO ROLE SONY_DE_DATA_STEWARD;
GRANT ROLE SONY_DE_FACTS_R TO ROLE SONY_DE_DATA_STEWARD;
GRANT ROLE SONY_DE_STG_R TO ROLE SONY_DE_DATA_STEWARD;

-- PII Admin: Secure data access
GRANT ROLE SONY_DE_SECURE_R TO ROLE SONY_DE_PII_ADMIN;
GRANT ROLE SONY_DE_DIMS_R TO ROLE SONY_DE_PII_ADMIN;

-- =============================================================================
-- GRANT FUNCTIONAL ROLES TO SYSADMIN (role hierarchy)
-- =============================================================================

GRANT ROLE SONY_DE_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_MARKETING_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_STUDIO_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_DATA_STEWARD TO ROLE SYSADMIN;
GRANT ROLE SONY_DE_PII_ADMIN TO ROLE SYSADMIN;

-- =============================================================================
-- WAREHOUSE ACCESS
-- =============================================================================

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_MARKETING_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_STUDIO_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_DATA_STEWARD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SONY_DE_PII_ADMIN;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Show all roles created
SHOW ROLES LIKE 'SONY_DE%';

-- Show role hierarchy
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES 
WHERE GRANTEE_NAME LIKE 'SONY_DE%' 
ORDER BY GRANTEE_NAME, GRANTED_ON;
